### ISSUE TITLE
Set custom HTTP runner headers from message

### ISSUE THREAD

**Issue by Kage** [leandro-lugaresi/message-cannon#61]
First, thank you for this awesome project!  It satisfies a major use-case I have.

I noticed that [consumer.go#L169](https://github.com/leandro-lugaresi/message-cannon/blob/2297b0f6d35c877803530f962c750c0adcf92d82/rabbit/consumer.go#L169) only sets four specific headers from the message payload.  I'd like to propose adding a config option for the http runner of something like `set_headers_from_message` which, when enabled, uses the `headers` index of the message to set all HTTP headers for the runner.  This allows for situations like mine where I'd like to set Authorization and X-Forwarded-For for the HTTP processor from the message payload, and otherwise be able to dynamically define the runner headers.

To put it briefly:

**As a** message-cannon user
**I want** to be able to define custom HTTP runner headers from the RMQ message payload
**So that** I can dynamically define headers like Authorization and X-Forwarded-For

**Comment by leandro-lugaresi** [comment]
@Kage You can use the new version and the message-cannon will automatically convert the rabbitMQ headers to HTTP headers, but we are only supporting simple headers values (not supporting `nil`, `byte` and `Table` values)

**Comment by Kage** [comment]
Awesome, thank you!
